name: deploy-container

on:
  push:
    branches:
      - main
    path:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    setps:
      - uses: actions/checkout@v2
      - id: dependencies
        run: npm install
      - id: build
        run: npm run build
